remove load_svn_dirs.pl
onOffice ticket #1578409

diff --git a/bin/commit-svn b/bin/commit-svn
--- a/bin/commit-svn
+++ b/bin/commit-svn
@@ -1,8 +1,6 @@
 #!/bin/sh
 
 # Deploys a tag of the plugin into the WP SVN.
-#
-# needs the package `subversion-tools` on Ubuntu
 
 TAG_PATH=tags
 TRUNK_PATH=trunk
@@ -16,19 +14,25 @@ if [ -z $SVNURL ]; then
 	exit 1
 fi
 
-if [ ! -z $NEW_TAG ]; then
-	grep "= $NEW_TAG =" readme.txt > /dev/null
-	CHANGELOG_ENTRY_EXISTS=$?
-	if [ $CHANGELOG_ENTRY_EXISTS -ne 0 ]; then
-		>&2 echo "Missing changelog entry for tag $NEW_TAG"
-		exit 2
-	fi
+if [ -z $NEW_TAG ]; then
+	>&2 echo "Tag argument is missing"
+	exit 2
 fi
 
-make release
-cd /tmp/onoffice
+grep "= $NEW_TAG =" readme.txt > /dev/null
 
-if [ ! -z "$NEW_TAG" -a "$2" = "--stable" ]; then
+if [ $? -ne 0 ]; then
+	>&2 echo "Missing changelog entry for tag $NEW_TAG"
+	exit 3
+fi
+
+RELEASE_DIR=`mktemp -d`
+>&2 echo "RELEASE_DIR is $RELEASE_DIR"
+
+PREFIX=$RELEASE_DIR make release
+cd "$RELEASE_DIR/onoffice"
+
+if [ "$2" = "--stable" ]; then
 	ed readme.txt <<EDSCRIPT
 7
 i
@@ -39,12 +43,13 @@ q
 EDSCRIPT
 fi
 
-cd $PPWDt
-svn_load_dirs -svn_username="${SVN_USER}" -svn_password="${SVN_PASSWORD}" -no_auto_exe -p "${PPWDt}/bin/svn-config.conf" -no_user_input ${SVNURL} ${TRUNK_PATH} /tmp/onoffice
+TEMPDIR_CHECKOUT=`mktemp -d`
+>&2 echo "TEMPDIR_CHECKOUT is $TEMPDIR_CHECKOUT"
 
->&2 echo $? was the return value
+svn co "${SVNURL}/${TRUNK_PATH}" "$TEMPDIR_CHECKOUT" || exit 4;
+svn import "$RELEASE_DIR/onoffice" "${SVNURL}/${TAG_PATH}/$NEW_TAG" --non-interactive -m "Create tag '$NEW_TAG'" --username "${SVN_USER}" --password "${SVN_PASSWORD}" || exit 5;
+svn merge --ignore-ancestry "${SVNURL}/${TRUNK_PATH}" "${SVNURL}/${TAG_PATH}/$NEW_TAG" "$TEMPDIR_CHECKOUT" || exit 6;
+cd "$TEMPDIR_CHECKOUT"
+svn commit -m "Update trunk to tag '$NEW_TAG'" --non-interactive --username "${SVN_USER}" --password "${SVN_PASSWORD}" || exit 7;
 
-rm -rf /tmp/svn_load_dirs*
-svn info "${SVNURL}${TAG_PATH}/$NEW_TAG" > /dev/null 2>&1 || \
-	svn copy --username "${SVN_USER}" --password "${SVN_PASSWORD}" --non-interactive "${SVNURL}/${TRUNK_PATH}" "${SVNURL}/${TAG_PATH}/$NEW_TAG" -m "Create tag '$NEW_TAG'"
 exit $?
